[[tests]]
name = "01"
input = ["./lab04", "max3", "1", "3", "2"]
expected = """
max3_c(1, 3, 2) = 3
max3_s(1, 3, 2) = 3
"""
rubric = 10

[[tests]]
name = "02"
input = ["./lab04", "max3", "-1", "-10", "-20"]
expected = """
max3_c(-1, -10, -20) = -1
max3_s(-1, -10, -20) = -1
"""
rubric = 10

[[tests]]
name = "03"
input = ["./lab04", "find_max", "5", "1", "2", "5", "3", "4"]
expected = """
find_max_c([1,2,5,3,4], 5) = 5
find_max_s([1,2,5,3,4], 5) = 5
"""
rubric = 10

[[tests]]
name = "04"
input = ["./lab04", "find_max", "10", "-1", "99", "1", "2", "3", "4", "5", "6", "7", "0"]
expected = """
find_max_c([-1,99,1,2,3,4,5,6,7,0], 10) = 99
find_max_s([-1,99,1,2,3,4,5,6,7,0], 10) = 99
"""
rubric = 10

[[tests]]
name = "05"
input = ["./lab04", "fib_rec", "5"]
expected = """
fib_rec_c(5) = 5
fib_rec_s(5) = 5
"""
rubric = 10

[[tests]]
name = "06"
input = ["./lab04", "fib_rec", "10"]
expected = """
fib_rec_c(10) = 55
fib_rec_s(10) = 55
"""
rubric = 10

[[tests]]
name = "07"
input = ["./lab04", "fib_rec", "19"]
expected = """
fib_rec_c(19) = 4181
fib_rec_s(19) = 4181
"""
rubric = 10

[[tests]]
name = "08"
input = ["./lab04", "stolower", "FooBar"]
expected = """
stolower_c(FooBar) = foobar
stolower_s(FooBar) = foobar
"""
rubric = 10

[[tests]]
name = "09"
input = ["./lab04", "stolower", "ALL UPPER CASE"]
expected = """
stolower_c(ALL UPPER CASE) = all upper case
stolower_s(ALL UPPER CASE) = all upper case
"""
rubric = 10

[[tests]]
name = "10"
input = ["./lab04", "stolower", "Coffee > $5.00 is too EXPENSIVE"]
expected = """
stolower_c(Coffee > $5.00 is too EXPENSIVE) = coffee > $5.00 is too expensive
stolower_s(Coffee > $5.00 is too EXPENSIVE) = coffee > $5.00 is too expensive
"""
rubric = 10
